### ISSUE TITLE
Support bundling npm dependencies

### ISSUE THREAD

**Issue by josh** [sstephenson/stitch#4]
Pull in source files from npm packages

Some pure js libraries to test against
- [abbrev-js](https://github.com/isaacs/abbrev-js)
- [async](https://github.com/caolan/async)
- [backbone](https://github.com/documentcloud/backbone)
- [coffee-script](https://github.com/jashkenas/coffee-script)
- [eco](https://github.com/sstephenson/eco)
- [inflection](https://github.com/gmosx/inflection)
- [js-yaml](https://github.com/visionmedia/js-yaml)
- [lingo](https://github.com/visionmedia/lingo)
- [markdown-js](https://github.com/evilstreak/markdown-js)
- [node-parallel](https://github.com/Tim-Smart/node-parallel)
- [step](https://github.com/creationix/step)
- [strscan-js](https://github.com/sstephenson/strscan-js)
- [underscore](https://github.com/documentcloud/underscore)
- [user-agent.js](https://github.com/visionmedia/user-agent.js)

**Comment by sstephenson** [comment]
nah
