### ISSUE TITLE
stitch.createPackage({ paths: ['file.js']}) fails

### ISSUE THREAD

**Issue by laurie71** [sstephenson/stitch#7]
If I create a package using stitch.createPackage({ paths: ['file.js']}) and then serve it via express, the served file only contains `throw "undefined"`, which isn't very helpful... ;-) Obviously 'paths' is expected to be a list of directories rather than a list of files, but it would be nice to get a more useful error thrown server-side when Stitch can't resolve a path.

**Comment by laurie71** [comment]
Found the problem: there are a couple of instances of 'callback <string>' that need to be 'callback new Error <string>' instead. Fixed on my fork in master 8be52f2. Pull request sent.

**Comment by sstephenson** [comment]
Thanks for the patch. Let's move this discussion over to the pull request: https://github.com/sstephenson/stitch/pull/9
